import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import {
  DayOfWeek,
  DeliveryScheduleStatus,
  KitchenStatus,
  NotificationCategory,
  Prisma,
  Subscription,
  SubscriptionBillingCycle,
  SubscriptionStatus,
} from '@prisma/client';
import { PrismaService } from '../../../../prisma/prisma.service';
import { NotificationsService } from '../notifications/notifications.service';
import { getIstCalendarDate, getIstDayOfWeek } from '../../../../common/utils/kitchen';
import { paginate, toSkip } from '../../../../common/dto/pagination.dto';
import { CreateSubscriptionDto } from '../../../customer/subscriptions/dto/customer-subscriptions.dto';

const DAY_MS = 86_400_000;
const DELIVERY_WINDOW_DAYS = 7;
/** Every MONTHLY cycle is a flat 4 weeks — avoids true-calendar-month arithmetic
 * both here and in pricing below, so the two never drift out of sync. */
const MONTHLY_CYCLE_WEEKS = 4;
/** Placeholder flat per-meal price — no kitchen-authored price list/plan-authoring feature exists yet. */
const PRICE_PER_MEAL_RS = 90;

const DAY_ORDER: DayOfWeek[] = [
  DayOfWeek.SUNDAY,
  DayOfWeek.MONDAY,
  DayOfWeek.TUESDAY,
  DayOfWeek.WEDNESDAY,
  DayOfWeek.THURSDAY,
  DayOfWeek.FRIDAY,
  DayOfWeek.SATURDAY,
];

type SubWithCustomer = Subscription & { user?: { id: string; fullName: string | null; phone: string; profileImage: string | null } | null };
type SubWithKitchen = Subscription & { kitchen?: { id: string; name: string; logoUrl: string | null; slug: string } | null };

/**
 * Subscriber management for the kitchen-partner app, plus the minimal
 * customer-facing surface needed to create/view/cancel a subscription (no
 * polished customer-app browsing UI is built this round — see the Round 4
 * plan's scope notes).
 *
 * No background-job infra exists in this codebase, so delivery/billing rows
 * are never generated by a cron — they're lazily backfilled on read (and once
 * eagerly on approve/resume), the same idiom `KitchenOperatingHours` and
 * `ReelCampaign` already use.
 */
@Injectable()
export class KitchenSubscriptionsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly notificationsService: NotificationsService,
  ) {}

  // ──────────────────────────────────────────────────────────────────────────
  // KITCHEN-FACING
  // ──────────────────────────────────────────────────────────────────────────

  async list(accountId: string, status?: SubscriptionStatus, q?: string, page = 1, limit = 20) {
    const kitchen = await this.requireKitchen(accountId);
    const where: Prisma.SubscriptionWhereInput = {
      kitchenId: kitchen.id,
      ...(status ? { status } : {}),
      ...(q ? { user: { fullName: { contains: q, mode: 'insensitive' } } } : {}),
    };

    const [rows, total, grouped] = await Promise.all([
      this.prisma.subscription.findMany({
        where,
        orderBy: { createdAt: 'desc' },
        skip: toSkip(page, limit),
        take: limit,
        include: { user: { select: { id: true, fullName: true, phone: true, profileImage: true } } },
      }),
      this.prisma.subscription.count({ where }),
      this.prisma.subscription.groupBy({ by: ['status'], where: { kitchenId: kitchen.id }, _count: { _all: true } }),
    ]);

    const counts = Object.fromEntries(Object.values(SubscriptionStatus).map((s) => [s, 0])) as Record<SubscriptionStatus, number>;
    grouped.forEach((g) => {
      counts[g.status] = g._count._all;
    });

    return { ...paginate(rows.map((r) => this.toSummaryDto(r)), page, limit, total), counts };
  }

  async findOne(accountId: string, id: string) {
    const kitchen = await this.requireKitchen(accountId);
    const sub = await this.requireOwned(kitchen.id, id);
    if (sub.status === SubscriptionStatus.ACTIVE) {
      await this.backfillDeliveries(sub);
      await this.backfillBilling(sub);
    }
    return this.toDetailDto(sub);
  }

  async approve(accountId: string, id: string) {
    const kitchen = await this.requireKitchen(accountId);
    const sub = await this.requireOwned(kitchen.id, id);
    if (sub.status !== SubscriptionStatus.PENDING) {
      throw new BadRequestException(`Cannot approve a subscription that is ${sub.status}`);
    }
    const updated = await this.prisma.subscription.update({
      where: { id },
      data: { status: SubscriptionStatus.ACTIVE, approvedAt: new Date() },
      include: { user: { select: { id: true, fullName: true, phone: true, profileImage: true } } },
    });
    await this.backfillDeliveries(updated);
    await this.backfillBilling(updated);
    return this.toDetailDto(updated);
  }

  async reject(accountId: string, id: string, reason: string) {
    const kitchen = await this.requireKitchen(accountId);
    const sub = await this.requireOwned(kitchen.id, id);
    if (sub.status !== SubscriptionStatus.PENDING) {
      throw new BadRequestException(`Cannot reject a subscription that is ${sub.status}`);
    }
    const updated = await this.prisma.subscription.update({
      where: { id },
      data: { status: SubscriptionStatus.REJECTED, rejectionReason: reason },
      include: { user: { select: { id: true, fullName: true, phone: true, profileImage: true } } },
    });
    return this.toDetailDto(updated);
  }

  async pause(accountId: string, id: string) {
    const kitchen = await this.requireKitchen(accountId);
    const sub = await this.requireOwned(kitchen.id, id);
    if (sub.status !== SubscriptionStatus.ACTIVE) {
      throw new BadRequestException(`Cannot pause a subscription that is ${sub.status}`);
    }
    const updated = await this.prisma.subscription.update({
      where: { id },
      data: { status: SubscriptionStatus.PAUSED, pausedAt: new Date() },
      include: { user: { select: { id: true, fullName: true, phone: true, profileImage: true } } },
    });
    return this.toDetailDto(updated);
  }

  async resume(accountId: string, id: string) {
    const kitchen = await this.requireKitchen(accountId);
    const sub = await this.requireOwned(kitchen.id, id);
    if (sub.status !== SubscriptionStatus.PAUSED) {
      throw new BadRequestException(`Cannot resume a subscription that is ${sub.status}`);
    }
    const updated = await this.prisma.subscription.update({
      where: { id },
      data: { status: SubscriptionStatus.ACTIVE, pausedAt: null },
      include: { user: { select: { id: true, fullName: true, phone: true, profileImage: true } } },
    });
    await this.backfillDeliveries(updated);
    await this.backfillBilling(updated);
    return this.toDetailDto(updated);
  }

  async dispatchDelivery(accountId: string, id: string, date: string) {
    const kitchen = await this.requireKitchen(accountId);
    await this.requireOwned(kitchen.id, id);
    const delivery = await this.requireTodayScheduledDelivery(id, date);
    return this.prisma.subscriptionDelivery.update({
      where: { id: delivery.id },
      data: { status: DeliveryScheduleStatus.DISPATCHED, dispatchedAt: new Date() },
    });
  }

  async skipDelivery(accountId: string, id: string, date: string, reason?: string) {
    const kitchen = await this.requireKitchen(accountId);
    await this.requireOwned(kitchen.id, id);
    const delivery = await this.requireTodayScheduledDelivery(id, date);
    return this.prisma.subscriptionDelivery.update({
      where: { id: delivery.id },
      data: { status: DeliveryScheduleStatus.SKIPPED, skipReason: reason },
    });
  }

  // ──────────────────────────────────────────────────────────────────────────
  // CUSTOMER-FACING (minimal — no polished browsing UI is built this round)
  // ──────────────────────────────────────────────────────────────────────────

  async createForCustomer(userId: string, dto: CreateSubscriptionDto) {
    const kitchen = await this.prisma.kitchen.findUnique({
      where: { id: dto.kitchenId },
      select: { id: true, status: true, accountId: true },
    });
    if (!kitchen || kitchen.status !== KitchenStatus.ACTIVE) {
      throw new BadRequestException('This kitchen is not accepting subscriptions right now');
    }

    const weeklyPrice = PRICE_PER_MEAL_RS * dto.mealsPerDay * dto.deliveryDays.length;
    const pricePerCycle = dto.billingCycle === SubscriptionBillingCycle.MONTHLY ? weeklyPrice * MONTHLY_CYCLE_WEEKS : weeklyPrice;

    const sub = await this.prisma.subscription.create({
      data: {
        userId,
        kitchenId: kitchen.id,
        planName: dto.planName,
        foodType: dto.foodType,
        mealsPerDay: dto.mealsPerDay,
        deliveryDays: dto.deliveryDays,
        deliveryTime: dto.deliveryTime,
        billingCycle: dto.billingCycle,
        pricePerCycle,
        specialInstructions: dto.specialInstructions,
        startDate: dto.startDate ? new Date(dto.startDate) : getIstCalendarDate(),
      },
      include: { kitchen: { select: { id: true, name: true, logoUrl: true, slug: true } } },
    });

    if (kitchen.accountId) {
      await this.notificationsService.create(
        kitchen.accountId,
        NotificationCategory.SUBSCRIPTION,
        'New subscription request',
        `${dto.planName} — ${dto.mealsPerDay} meal(s)/day, ${dto.deliveryDays.length} day(s)/week. Tap to review.`,
        { subscriptionId: sub.id },
      );
    }

    return this.toDetailDto(sub);
  }

  async listForCustomer(userId: string) {
    const rows = await this.prisma.subscription.findMany({
      where: { userId },
      orderBy: { createdAt: 'desc' },
      include: { kitchen: { select: { id: true, name: true, logoUrl: true, slug: true } } },
    });
    return rows.map((r) => this.toSummaryDto(r));
  }

  async findOneForCustomer(userId: string, id: string) {
    const sub = await this.prisma.subscription.findUnique({
      where: { id },
      include: { kitchen: { select: { id: true, name: true, logoUrl: true, slug: true } } },
    });
    if (!sub) throw new NotFoundException('Subscription not found');
    if (sub.userId !== userId) throw new ForbiddenException('This subscription does not belong to you');
    return this.toDetailDto(sub);
  }

  async cancelForCustomer(userId: string, id: string) {
    const sub = await this.prisma.subscription.findUnique({
      where: { id },
      include: { kitchen: { select: { id: true, name: true, logoUrl: true, slug: true } } },
    });
    if (!sub) throw new NotFoundException('Subscription not found');
    if (sub.userId !== userId) throw new ForbiddenException('This subscription does not belong to you');
    if (sub.status === SubscriptionStatus.CANCELLED || sub.status === SubscriptionStatus.REJECTED) {
      return this.toDetailDto(sub);
    }
    const updated = await this.prisma.subscription.update({
      where: { id },
      data: { status: SubscriptionStatus.CANCELLED, cancelledAt: new Date() },
      include: { kitchen: { select: { id: true, name: true, logoUrl: true, slug: true } } },
    });
    return this.toDetailDto(updated);
  }

  // ──────────────────────────────────────────────────────────────────────────
  // INTERNAL
  // ──────────────────────────────────────────────────────────────────────────

  /** Rolling today..+6 delivery window, idempotent via the unique constraint. */
  private async backfillDeliveries(sub: Subscription) {
    const today = getIstCalendarDate();
    const startDow = getIstDayOfWeek();
    const startIdx = DAY_ORDER.indexOf(startDow);

    const rows: Prisma.SubscriptionDeliveryCreateManyInput[] = [];
    for (let i = 0; i < DELIVERY_WINDOW_DAYS; i++) {
      const dow = DAY_ORDER[(startIdx + i) % 7];
      if (!sub.deliveryDays.includes(dow)) continue;
      rows.push({ subscriptionId: sub.id, date: new Date(today.getTime() + i * DAY_MS) });
    }
    if (!rows.length) return;
    await this.prisma.subscriptionDelivery.createMany({ data: rows, skipDuplicates: true });
  }

  /** Every billing-cycle boundary since startDate that has already passed, idempotent. */
  private async backfillBilling(sub: Subscription) {
    const today = getIstCalendarDate();
    const cycleDays = sub.billingCycle === SubscriptionBillingCycle.MONTHLY ? MONTHLY_CYCLE_WEEKS * 7 : 7;

    const rows: Prisma.SubscriptionBillingEventCreateManyInput[] = [];
    let cursor = new Date(sub.startDate);
    let guard = 0;
    while (cursor.getTime() <= today.getTime() && guard < 500) {
      rows.push({ subscriptionId: sub.id, cycleStart: cursor, amount: sub.pricePerCycle });
      cursor = new Date(cursor.getTime() + cycleDays * DAY_MS);
      guard++;
    }
    if (!rows.length) return;
    await this.prisma.subscriptionBillingEvent.createMany({ data: rows, skipDuplicates: true });
  }

  private async requireTodayScheduledDelivery(subscriptionId: string, date: string) {
    const today = getIstCalendarDate();
    const requested = new Date(date);
    if (Number.isNaN(requested.getTime()) || requested.getTime() !== today.getTime()) {
      throw new BadRequestException("Only today's delivery can be dispatched or skipped");
    }
    const delivery = await this.prisma.subscriptionDelivery.findUnique({
      where: { subscriptionId_date: { subscriptionId, date: requested } },
    });
    if (!delivery) throw new NotFoundException('No delivery scheduled for that date');
    if (delivery.status !== DeliveryScheduleStatus.SCHEDULED) {
      throw new BadRequestException(`This delivery is already ${delivery.status}`);
    }
    return delivery;
  }

  private async requireOwned(kitchenId: string, id: string): Promise<SubWithCustomer> {
    const sub = await this.prisma.subscription.findUnique({
      where: { id },
      include: { user: { select: { id: true, fullName: true, phone: true, profileImage: true } } },
    });
    if (!sub) throw new NotFoundException('Subscription not found');
    if (sub.kitchenId !== kitchenId) {
      throw new ForbiddenException('This subscription does not belong to your kitchen');
    }
    return sub;
  }

  private async requireKitchen(accountId: string) {
    const kitchen = await this.prisma.kitchen.findUnique({ where: { accountId }, select: { id: true } });
    if (!kitchen) throw new BadRequestException('Complete onboarding to create your kitchen first');
    return kitchen;
  }

  private toSummaryDto(sub: SubWithCustomer | SubWithKitchen) {
    return {
      id: sub.id,
      planName: sub.planName,
      foodType: sub.foodType,
      mealsPerDay: sub.mealsPerDay,
      deliveryDays: sub.deliveryDays,
      deliveryTime: sub.deliveryTime,
      billingCycle: sub.billingCycle,
      pricePerCycle: sub.pricePerCycle,
      status: sub.status,
      startDate: sub.startDate,
      approvedAt: sub.approvedAt,
      pausedAt: sub.pausedAt,
      cancelledAt: sub.cancelledAt,
      createdAt: sub.createdAt,
      ...('user' in sub && sub.user !== undefined ? { customer: sub.user } : {}),
      ...('kitchen' in sub && sub.kitchen !== undefined ? { kitchen: sub.kitchen } : {}),
    };
  }

  private async toDetailDto(sub: SubWithCustomer | SubWithKitchen) {
    const [deliveries, billingEvents] = await Promise.all([
      this.prisma.subscriptionDelivery.findMany({ where: { subscriptionId: sub.id }, orderBy: { date: 'asc' } }),
      this.prisma.subscriptionBillingEvent.findMany({ where: { subscriptionId: sub.id }, orderBy: { cycleStart: 'desc' } }),
    ]);

    return {
      ...this.toSummaryDto(sub),
      specialInstructions: sub.specialInstructions,
      rejectionReason: sub.rejectionReason,
      deliverySchedule: deliveries.map((d) => ({ date: d.date, status: d.status, dispatchedAt: d.dispatchedAt, skipReason: d.skipReason })),
      billingHistory: billingEvents.map((b) => ({ cycleStart: b.cycleStart, amount: b.amount, paymentStatus: b.paymentStatus })),
    };
  }
}
